apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-myobs-prometheus
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/raviagg/myprometheus
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: ns-myobs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
