apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-myobs-grafana
  namespace: ns-myobs

spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-myobs-grafana

  template:
    metadata:
      labels:
        app: app-myobs-grafana

    spec:
      containers:
        - name: container-myobs-grafana
          image: grafana/grafana

          ports:
            - containerPort: 3000

          volumeMounts:
            - name: vm-myobs-grafana-storage
              mountPath: /var/lib/grafana

      volumes:
        - name: vm-myobs-grafana-storage
          persistentVolumeClaim:
            claimName: pvc-myobs-grafana
